name:                Naproche-SAD
version:             0.1.0.0
github:              "naproche-community/naproche"
license:             GPL-3

extra-source-files:
- README.md

description:         <https://github.com/naproche-community/naproche>

flags:
  debug:
    description: "Enable special debugging support"
    manual: true
    default: false


when:
  condition: flag(debug)
  dependencies:
  - haskell-stack-trace-plugin
  ghc-options:
  - -fplugin=StackTrace.Plugin
  - -Weverything
  - -Wno-unsafe
  - -Wno-implicit-prelude

dependencies:
- base >= 4.7 && < 5
- array
- bytestring
- containers
- ghc-prim
- megaparsec
- mtl
- network
- process
- split
- temporary
- text
- threads
- time
- transformers
- uuid
- flex

default-extensions:
  - GeneralizedNewtypeDeriving
  - InstanceSigs
  - LambdaCase
  - PartialTypeSignatures
  - ScopedTypeVariables
  - ImportQualifiedPost

ghc-options:
  - -O2
  - -Wall
  - -fno-warn-unused-do-bind
  - -fno-warn-unused-matches
  - -fno-warn-name-shadowing

library:
  source-dirs:
    - src
    - Isabelle/src
  exposed-modules:
    - Isabelle.File
    - Isabelle.Server
    - Isabelle.Byte_Message
    - Isabelle.Properties
    - Isabelle.UTF8
    - Isabelle.XML
    - Isabelle.YXML
    - Isabelle.UUID
    - Isabelle.Isabelle_Thread
    - Isabelle.Library
    - Isabelle.Naproche
    - SAD.API
    - SAD.Main
    - SAD.Core.ProofTask
    - SAD.Data.Formula.Kit
    - SAD.ForTheL.Base
    - SAD.ForTheL.Structure
    - SAD.Import.Reader
    - SAD.Parser.Combinators
    - SAD.Parser.Primitives
    - SAD.Parser.Token

executables:
  Naproche-SAD:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - Naproche-SAD
    when:
    - condition: false
      other-modules: Paths_Naproche_SAD

tests:
  Naproche-SAD-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - Naproche-SAD
