name:                SAD3
version:             0.1.0.0
github:              "PeterKoepke/SAD3"
license:             GPL3

extra-source-files:
- README.md

description:         <https://github.com/PeterKoepke/SAD3>

dependencies:
- base >= 4.7 && < 5
- containers
- process
- time
- mtl
- transformers
- bytestring
- utf8-string

library:
  source-dirs:
    - src
    - Isabelle/src

executables:
  SAD3-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - SAD3

tests:
  SAD3-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - SAD3
