#!/usr/bin/env bash
#
# DESCRIPTION: build Isabelle/Naproche jar and executable

set -e

cd "$NAPROCHE_HOME"


echo "### Building Isabelle/Scala module: $NAPROCHE_JAR"

isabelle scala_build


echo "### Building Isabelle/Naproche Haskell modules"

isabelle build -o naproche_server=false -e -d. Naproche-Build


echo "### Building executable program: $NAPROCHE_EXE"

isabelle ghc_stack build

mkdir -p "$NAPROCHE_EXE_DIR"
cp "$(standard_path "$(isabelle ghc_stack path --local-install-root)/bin/Naproche-SAD")" \
  "$NAPROCHE_EXE_DIR"
