{- generated by Isabelle -}

{-  Title:      Isabelle/Bytes.hs
    Author:     Makarius
    LICENSE:    BSD 3-clause (Isabelle)

Compact byte strings.

See "$ISABELLE_HOME/src/Pure/General/bytes.ML"
and "$ISABELLE_HOME/src/Pure/General/bytes.scala".
-}

module Isabelle.Bytes (
  Bytes
)
where

import Data.ByteString.Short (ShortByteString)

type Bytes = ShortByteString
