{- generated by Isabelle -}

{-
Authors: Makarius (2021)

Constants for Isabelle/Naproche.
-}

{-# LANGUAGE OverloadedStrings #-}

module Isabelle.Naproche
where

import Isabelle.Bytes (Bytes)


-- options

naproche_prove, naproche_check, naproche_skipfail :: Bytes
naproche_prove = "naproche_prove"
naproche_check = "naproche_check"
naproche_skipfail = "naproche_skipfail"

naproche_pos_id, naproche_pos_file, naproche_pos_shift :: Bytes
naproche_pos_id = "naproche_pos_id"
naproche_pos_file = "naproche_pos_file"
naproche_pos_shift = "naproche_pos_shift"


-- message origin

origin, origin_main, origin_export, origin_forthel, origin_parser,
  origin_reasoner, origin_simplifier, origin_thesis, origin_translate :: Bytes
origin = "origin"
origin_main = "Main"
origin_export = "Export"
origin_forthel = "ForTheL"
origin_parser = "Parser"
origin_reasoner = "Reasoner"
origin_simplifier = "Simplifier"
origin_thesis = "Thesis"
origin_translate = "Translation"


-- server commands
-- (see "$NAPROCHE_HOME/src/SAD/Main.hs")
-- (see "$NAPROCHE_HOME/Isabelle/src/scala/prover_server.scala")

prover_args :: Bytes
prover_args = "prover_args"

uuid_command :: Bytes
uuid_command = "uuid"

cancel_command :: Bytes
cancel_command = "cancel"

forthel_command :: Bytes
forthel_command = "forthel"


prover_command :: Bytes
prover_command = "prover"

prover_name :: Bytes
prover_name = "name"

prover_timeout :: Bytes
prover_timeout = "timeout"

prover_result :: Bytes
prover_result = "result"

prover_return_code :: Bytes
prover_return_code = "return_code"

kill_command :: Bytes
kill_command = "kill"
