{- generated by Isabelle -}

{-
Authors: Makarius (2021)

Constants for Isabelle/Naproche.
-}

{-# LANGUAGE OverloadedStrings #-}

module Isabelle.Naproche
where

import Isabelle.Bytes (Bytes)


-- options

naproche_prove, naproche_check, naproche_skipfail :: Bytes
naproche_prove = "naproche_prove"
naproche_check = "naproche_check"
naproche_skipfail = "naproche_skipfail"


-- environment

naproche_pide, naproche_pos_file, naproche_pos_shift :: Bytes
naproche_pide = "NAPROCHE_PIDE"
naproche_pos_file = "NAPROCHE_POS_FILE"
naproche_pos_shift = "NAPROCHE_POS_SHIFT"


-- message origin

origin, origin_main, origin_export, origin_forthel, origin_parser,
  origin_reasoner, origin_simplifier, origin_thesis, origin_translate :: Bytes
origin = "origin"
origin_main = "Main"
origin_export = "Export"
origin_forthel = "ForTheL"
origin_parser = "Parser"
origin_reasoner = "Reasoner"
origin_simplifier = "Simplifier"
origin_thesis = "Thesis"
origin_translate = "Translation"


-- server commands
-- (see "$NAPROCHE_HOME/src/SAD/Main.hs")
-- (see "$NAPROCHE_HOME/Isabelle/src/scala/prover_server.scala")

command_args :: Bytes
command_args = "command_args"

cancel_command :: Bytes
cancel_command = "cancel"

forthel_command :: Bytes
forthel_command = "forthel"


prover_command :: Bytes
prover_command = "prover"

prover_name :: Bytes
prover_name = "name"

prover_timeout :: Bytes
prover_timeout = "timeout"

prover_result :: Bytes
prover_result = "result"

prover_return_code :: Bytes
prover_return_code = "return_code"

kill_command :: Bytes
kill_command = "kill"
