{- generated by Isabelle -}

{-  Title:      Isabelle/UUID.hs
    Author:     Makarius
    LICENSE:    BSD 3-clause (Isabelle)

Universally unique identifiers.

See "$ISABELLE_HOME/src/Pure/General/uuid.scala".
-}

module Isabelle.UUID (T, random, random_string, parse)
where

import Data.UUID (UUID)
import qualified Data.UUID as UUID
import Data.UUID.V4 (nextRandom)


type T = UUID

random :: IO T
random = nextRandom

random_string :: IO String
random_string = UUID.toString <$> random

parse :: String -> Maybe T
parse = UUID.fromString
