name:                naproche
version:             0.1.0.0
github:              "naproche/naproche"
license:             GPL-3

description:         <https://github.com/naproche/naproche>

dependencies:
- base >= 4.7 && < 5
- array
- bytestring
- containers
- ghc-prim
- megaparsec
- mtl
- network
- process
- split
- temporary
- text
- threads
- time
- transformers
- uuid
- Naproche-SAD
- Isabelle

default-extensions:
  - GeneralizedNewtypeDeriving
  - InstanceSigs
  - LambdaCase
  - PartialTypeSignatures
  - ScopedTypeVariables

ghc-options:
  - -O2
  - -Wall
  - -fno-warn-unused-do-bind
  - -fno-warn-unused-matches
  - -fno-warn-name-shadowing

executables:
  Naproche-SAD:
    main:                Main.hs
    source-dirs:         src
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - Naproche-SAD
    when:
    - condition: false
      other-modules: Paths_Naproche_SAD

tests:
  Naproche-SAD-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - Naproche-SAD
