[synonym bound/-s] 
[synonym belong/-s]
[synonym cardinal/-s]
[synonym divide/-s]
[synonym element/-s]
[synonym function/-s]
[synonym infimum/infima]
[synonym lattice/-s]
[synonym number/-s]
[synonym ordinal/-s]
[synonym point/-s]
[synonym reduct/-s]
[synonym set/-s]
[synonym subset/-s] 
[synonym supremum/suprema]
[synonym surject/-s]
[synonym system/-s]
  
