#!/usr/bin/env bash
#
# DESCRIPTION: build Isabelle/Naproche jar and executable

set -e

cd "$NAPROCHE_HOME"

isabelle jedit -b

echo "### Building Isabelle/Scala module: $NAPROCHE_JAR"
isabelle build -e -D Isabelle

echo "### Building executable program: $NAPROCHE_EXE"
isabelle ghc_stack build

mkdir -p "$NAPROCHE_EXE_DIR"
cp "$(standard_path "$(isabelle ghc_stack path --local-install-root)/bin/Naproche-SAD")" \
  "$NAPROCHE_EXE_DIR"
